import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import Subscribe from "@/components/common/Subscribe";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ShopCenter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Subscribe />
        <Footer />
      </body>
    </html>
  );
}
